### ISSUE TITLE
Refine Onboarding

### ISSUE THREAD

**Issue by baiIey** [patrickwong/photo-app#15]
Prompt users that we'll ask permissions for photo gallery, and provide fallback if users opt out.

Also, provide a signal to illustrate how to re-enable iOS permissions the app my need.

/cc @patrickwong

**Comment by patrickwong** [comment]
this was on my list of to-dos for the mock ups, thanks!

—

**Comment by baiIey** [comment]
Rock on!

**Comment by patrickwong** [comment]
Done

**Comment by baiIey** [comment]
Good stuff. I may re-open or clone this issue as we build this.
