### ISSUE TITLE
Check company name and filepath

### ISSUE THREAD

**Issue by baiIey** [patrickwong/photo-app#2]
Can you confirm that the project's organization name and filename prefix are aligned with your Apple Dev account before we get too far into the project?

In Xcode:
[org-name].[product-name]

Just want to make sure we can push this to the Store when all's said and done.

-b

**Comment by patrickwong** [comment]
thanks for being on top of this! I'll make sure to check this

—

**Comment by nicobories** [comment]
Have you thought of any company names @patrickwong ?

**Comment by patrickwong** [comment]
@baiIey just checked -- name should be "Patrick-Wong" instead of "patrickwong"

**Comment by baiIey** [comment]
@patrickwong & @nbories-okta,

I updated the organization and bundle identifier so that they read Patrick-Wong.Photo-App and Patrick Wong respectively.

We should keep the idea of a contract with cost and revenue split, and perhaps creating a trust-like company, should we decide to monetize this app in the future. By the way, this is all sitting under a MIT license on a public repository, at the moment.
